[libraries]
neoforge = { group = "net.neoforged", name = "neoforge", version = "21.11.42" }

[plugins]
neoforge-moddev = { id = "net.neoforged.moddev", version = "2.0.141" }
lombok = { id = "io.freefair.lombok", version = "9.4.0"}
spotless = { id = "com.diffplug.spotless", version = "8.4.0" }
modmuss50-publish = { id = "me.modmuss50.mod-publish-plugin", version = "1.1.0" }